### ISSUE TITLE
Cache driver default doesn't use env CACHE_DRIVER

### ISSUE THREAD

**Issue by fede91it** [hamburgscleanest/guzzle-advanced-throttle#12]
From the configuration file **laravel-guzzle-throttle.php** the driver is set to `default` as standard, however the default driver set by **CACHE_DRIVER** in the **.env** file was ignored and it rises a **hamburgscleanest\GuzzleAdvancedThrottle\Exceptions\RedisDatabaseNotSetException**.

Everything works correctly if I set the **driver** value to `env('CACHE_DRIVER')` instead of `'default'`.

Why this behaviour?

**Comment by Chroma91** [comment]
Hey @fede91it, it's something I probably overlooked while developing because I never changed the environment variable. I'm open for a PR that changes this behavior. Otherwise I'll implement it myself after the weekend. Thanks for bringing that up!

**Comment by fede91it** [comment]
Thank you

**Comment by Chroma91** [comment]
This issue will be solved with hamburgscleanest/laravel-guzzle-throttle#4.
